export const metadata = {
  title: "Contacts",
  description: "Contacts page generated by next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
